name: deploy
on: workflow_dispatch
jobs:
  docker-image-build:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Build Environment
      uses: docker/setup-buildx-action@v3
    - name: Build and save docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: hyuabot-database-initializer:latest
        no-cache: true
