name: deploy
on: workflow_dispatch
jobs:
  docker-image-build:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Build Environment
      uses: docker/setup-buildx-action@v3
    - name: Build and save docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: localhost:32000/hyuabot/hyuabot-database-initializer:latest
        no-cache: true
    - name: Push docker image
      run: |
        docker push localhost:32000/hyuabot/hyuabot-database-initializer:latest
    - name: Remove docker image
      run: |
        docker rmi localhost:32000/hyuabot/hyuabot-database-initializer:latest
